services:
  frontend:
    build:
      context: ./front-end
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./back-end
    container_name: backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/users_db
      - SECRET_KEY=s4muel@2025
    depends_on:
      - db

volumes:
  postgres_data:
